# Site settings
title: BSidesLuanda
description: >
  === Stay tuned we are setting up, Event comming soon to Luanda - Angola ===
                    
  Security BSidesLDA is a regional Security B-Sides held in Luanda.
  It operates under the umbrella principles of Security B-Sides as a larger community project within information security.
  Each Security B-Sides is a community-driven framework for building events for, and by, information security practitioners.
  The goal is to expand the spectrum of conversation beyond the traditional confines of space and time.
  It creates opportunities for individuals to both present and participate in an intimate atmosphere that encourages collaboration.
  It is an intense event with discussions, demos, and interaction from participants.
  It is where conversations for the next-big-thing are happening.
url: 'http://www.bsidesluanda.org'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'BSidesLuanda'
  email: admin@bsidesluanda.org
  twitter_username: BSidesLDA
  #facebook_username: joshgerdes
  #github_username:  joshgerdes
  #linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
